# Generated by Django 4.1.7 on 2023-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=120)),
            ],
        ),
    ]
