# Generated by Django 4.1.7 on 2023-04-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
