# Generated by Django 4.1.7 on 2023-04-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0010_stud_leave_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_leave_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('leave_date', models.DateField()),
                ('status', models.CharField(max_length=25, null=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuition_app.teacher_table1')),
            ],
        ),
    ]
