# Generated by Django 4.1.7 on 2023-04-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0012_tuition_table1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition_table1',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='tuition_table1',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tuition_table1',
            name='student',
        ),
        migrations.DeleteModel(
            name='tuition_table',
        ),
        migrations.DeleteModel(
            name='tuition_table1',
        ),
    ]
