# Generated by Django 4.1.7 on 2023-04-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0020_task_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task_table',
        ),
    ]
