# Generated by Django 4.1.7 on 2023-04-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0025_task_submitted_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task_submitted_table',
        ),
    ]
