# Generated by Django 4.1.7 on 2023-04-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0026_delete_task_submitted_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_submitted_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('document', models.FileField(upload_to='doc/')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuition_app.batch_table')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuition_app.course_table')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuition_app.student_table')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuition_app.task_table')),
            ],
        ),
    ]
