from tuition_app import views
from django.urls import path

urlpatterns=[
    path('',views.home,name='home'),
    path('signup/',views.signup,name='signup'),
    path('login_page/',views.login_page,name='login_page'),
    path('login/',views.login,name='login'),
    path('admin_home/',views.admin_home,name='admin_home'),
    path('add_course/',views.add_course,name='add_course'),
    path('add_batch/',views.add_batch,name='add_batch'),
    path('tea_signup/',views.tea_signup,name='tea_signup'),
    path('user_home/',views.user_home,name='user_home'),
    path('user_home1/',views.user_home1,name='user_home1'),

    path('stud_signup/',views.stud_signup,name='stud_signup'),
    path('student_signup/',views.student_signup,name='student_signup'),
    path('subject_details/',views.subject_details,name='subject_details'),
    path('join_course/<int:pk>/',views.join_course,name='join_course'),
    path('joined_course/<int:pk>',views.joined_course,name='joined_course'),
    path('time_table_page/',views.time_table_page,name='time_table_page'),
    path('add_time_table/',views.add_time_table,name='add_time_table'),
    path('view_timetable/',views.view_timetable,name='view_timetable'),
    path('stud_subject_list/',views.stud_subject_list,name='stud_subject_list'),
    path('stud_timetable/<int:pk>',views.stud_timetable,name='stud_timetable'),
    path('stud_leave_page/',views.stud_leave_page,name='stud_leave_page'),
    path('stud_leave/',views.stud_leave,name='stud_leave'),
    path('leave_list_page/',views.leave_list_page,name='leave_list_page'),
    path('allow/<int:pk>',views.allow,name='allow'),
    path('denay/<int:pk>',views.denay,name='denay'),
    path('stud_leave_list/',views.stud_leave_list,name='stud_leave_list'),
    path('tea_leave_page/',views.tea_leave_page,name='tea_leave_page'),
    path('tea_leave/',views.tea_leave,name='tea_leave'),
    path('teacher_leave_page/',views.teacher_leave_page,name='teacher_leave_page'),
    path('tallow/<int:pk>',views.tallow,name='tallow'),
    path('tdenay/<int:pk>',views.tdenay,name='tdenay'),
    path('teacher_applied_leave_list/',views.teacher_applied_leave_list,name='teacher_applied_leave_list'),
    path('attendence_page/<int:pk>',views.attendence_page,name='attendence_page'),
    path('take_attendence_page/<int:pk>',views.take_attendence_page,name='take_attendence_page'),
    path('submit_attendence/<int:pk>',views.submit_attendence,name='submit_attendence'),
    path('edit_attendence_page/<int:pk>',views.edit_attendence_page,name='edit_attendence_page'),
    path('edit_attendence/<int:pk>',views.edit_attendence,name='edit_attendence'),
    path('syllabus/',views.syllabus,name='syllabus'),
    path('add_syllabus/',views.add_syllabus,name='add_syllabus'),
    path('view_syllabus/',views.view_syllabus,name='view_syllabus'),
    path('list_syllabus/<int:pk>',views.list_syllabus,name='list_syllabus'),
    path('doc_upload_page/',views.doc_upload_page,name='doc_upload_page'),
    path('doc_upload/',views.doc_upload,name='doc_upload'),
    path('list_study_material/<int:pk>',views.list_study_material,name='list_study_material'),
    path('download_topic/<int:pk>',views.download_topic,name='download_topic'),
    path('subject_mark_page/',views.subject_mark_page,name='subject_mark_page'),
    path('student_mark/<int:pk>',views.student_mark,name='student_mark'),
    path('mark_enter_page/<int:pk>',views.mark_enter_page,name='mark_enter_page'),
    path('submit_mark/<int:pk>',views.submit_mark,name='submit_mark'),
    path('stud_exam_mark/<int:pk>',views.stud_exam_mark,name='stud_exam_mark'),
    path('stud_profile_page/',views.stud_profile_page,name='stud_profile_page'),
    path('edit_stud_form/',views.edit_stud_form,name='edit_stud_form'),
    path('stud_edit_profile/<int:pk>',views.stud_edit_profile,name='stud_edit_profile'),
    path('tea_profile_page/',views.tea_profile_page,name='tea_profile_page'),
    path('edit_tea_form/',views.edit_tea_form,name='edit_tea_form'),
    path('teacher_edit_profile/<int:pk>',views.teacher_edit_profile,name='teacher_edit_profile'),
    path('teacher_list/',views.teacher_list,name='teacher_list'),
    path('stud_batch_list',views.stud_batch_list,name='stud_batch_list'),
    path('student_list/<int:pk>',views.student_list,name='student_list'),
    path('load_home/',views.load_home,name='load_home'),
    path('view_more/',views.view_more,name='view_more'),
    path('send_mail_page/',views.send_mail_page,name='send_mail_page'),
    path('submit_mail/',views.submit_mail,name='submit_mail'),
    path('logout/',views.logout,name='logout'),
    path('add_task_page/',views.add_task_page,name='add_task_page'),
    path('submit_task/',views.submit_task,name='submit_task'),
    path('task_list_page/<int:pk>',views.task_list_page,name='task_list_page'),
    path('task_upload_page/<int:pk>',views.task_upload_page,name='task_upload_page'),
    path('task_upload/<int:pk>',views.task_upload,name='task_upload'),
    path('completed_task_list/<int:pk>',views.completed_task_list,name='completed_task_list'),
    path('task_batch_page/',views.task_batch_page,name='task_batch_page'),
    path('task_given_list/<int:pk>',views.task_given_list,name='task_given_list'),
    path('task_submited_students/<int:pk>',views.task_submited_students,name='task_submited_students'),
    path('feedback_page/',views.feedback_page,name='feedback_page'),
    path('give_feedback/',views.give_feedback,name='give_feedback'),
    path('view_feedback_page/',views.view_feedback_page,name='view_feedback_page'),
    path('task_sub_page/',views.task_sub_page,name='task_sub_page'),
    path('study_material_page/',views.study_material_page,name='study_material_page'),


]


